project:
  type: website
  output-dir: _site
  preview:
    port: 4040
    browser: true

page-layout: full

execute:
  freeze: auto
  cache: true
  echo: true
  warning: true
  message: true
  error: true # errors will not stop rendering!

website:
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph: true
  search: true
  twitter-card: true
  title: "Applied Math for Creative Coders"
  site-url: "https://mathforcoders.netlify.app"
  repo-url: https://github.com/arvindvenkatadri/mathforcoders
  description: "This is Arvind V.'s website for teaching Maths and Systems for Creative Coders"
  favicon: "content/materials/icon-park-twotone--concept-sharing.svg"
  google-analytics: "" 
  reader-mode: true
  
  navbar:
    background: info
    foreground: secondary
    pinned: false
    collapse: true
    collapse-below: lg
      
    right:
      - icon: github
        href: https://github.com/arvindvenkatadri/creativemath
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: linkedin
        href: https://www.linkedin.com/in/arvindvenkatadri
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com

  sidebar:
    style: "docked"
    background: secondary
    alignment: left
    collapse-level: 2
    search: true
    logo: "content/materials/images/Catterpillar.jpg"
    contents:

      - section: "Teaching"
        href: content/courses/listing.qmd
        contents: 
         
          - section: "Math Models for Creative Coders"
            href: content/courses/MathModelsDesign/listing.qmd
            contents: 
              - section: "Maths Basics"
                href: content/courses/MathModelsDesign/Modules/05-Maths/listing.qmd
                contents:
                - content/courses/MathModelsDesign/Modules/05-Maths/10-Complex/index.qmd
                - content/courses/MathModelsDesign/Modules/05-Maths/20-Vectors/index.qmd
#               - content/courses/MathModelsDesign/Modules/05-Maths/30-Probability/index.qmd
                - content/courses/MathModelsDesign/Modules/05-Maths/50-Matrices/index.qmd            
                - content/courses/MathModelsDesign/Modules/05-Maths/60-Orthogonality/index.qmd            
                - content/courses/MathModelsDesign/Modules/05-Maths/70-MultiDimensionGeometry/index.qmd            

              - section: "Tech"
                href: content/courses/MathModelsDesign/Modules/500-Tech/listing.qmd
                contents:
                - content/courses/MathModelsDesign/Modules/500-Tech/05-Tools/index.qmd
                - content/courses/MathModelsDesign/Modules/500-Tech/20-AddingLibrariesToP5Js/index.qmd
                - content/courses/MathModelsDesign/Modules/500-Tech/30-Constructors/index.qmd
                - content/courses/MathModelsDesign/Modules/500-Tech/50-OSC/index.qmd            
              - section: "Geometry"
                href: content/courses/MathModelsDesign/Modules/25-Geometry/listing.qmd
                contents:
                - content/courses/MathModelsDesign/Modules/25-Geometry/10-Circles/index.qmd
                - content/courses/MathModelsDesign/Modules/25-Geometry/20-ComplexNumbers/index.qmd
                - content/courses/MathModelsDesign/Modules/25-Geometry/30-Fractals/index.qmd
#               - content/courses/MathModelsDesign/Modules/25-Geometry/40-IteratedFunctions/index.qmd 
                - content/courses/MathModelsDesign/Modules/25-Geometry/42-AffineFractals/index.qmd 
#               - content/courses/MathModelsDesign/Modules/25-Geometry/44-ChaosGames/index.qmd 
                - content/courses/MathModelsDesign/Modules/25-Geometry/50-LSystems/index.qmd 
                - content/courses/MathModelsDesign/Modules/25-Geometry/60-Kolams/index.qmd 
#               - content/courses/MathModelsDesign/Modules/25-Geometry/70-NonEuclidean/index.qmd 
#               - content/courses/MathModelsDesign/Modules/25-Geometry/200-Art/index.qmd
 
              - section: "Media"
                href: content/courses/MathModelsDesign/Modules/35-Media/listing.qmd
                contents:
                - content/courses/MathModelsDesign/Modules/35-Media/10-FourierSeries/index.qmd
                - content/courses/MathModelsDesign/Modules/35-Media/12-AdditiveSynth/index.qmd
#               - content/courses/MathModelsDesign/Modules/35-Media/14-GrainSynth/index.qmd
#               - content/courses/MathModelsDesign/Modules/35-Media/16-ModulationSynth/index.qmd
#               - content/courses/MathModelsDesign/Modules/35-Media/18-NonlinearSynth/index.qmd
                - content/courses/MathModelsDesign/Modules/35-Media/20-MakingNoise/index.qmd
                - content/courses/MathModelsDesign/Modules/35-Media/99-KarplusStrong/index.qmd
#               - content/courses/MathModelsDesign/Modules/35-Media/30-Video/index.qmd 
#               - content/courses/MathModelsDesign/Modules/35-Media/40-Text/index.qmd 
                
              # - section: "Uncertainty"
              #   href: content/courses/MathModelsDesign/Modules/45-Uncertainty/listing.qmd
              #   contents:                 
              #   - content/courses/MathModelsDesign/Modules/45-Uncertainty/10-Chance/index.qmd 
              #   - content/courses/MathModelsDesign/Modules/45-Uncertainty/20-Chaos/index.qmd 
              #   - content/courses/MathModelsDesign/Modules/45-Uncertainty/30-Agents/index.qmd
              #   - content/courses/MathModelsDesign/Modules/45-Uncertainty/40-Time/index.qmd
              #   - content/courses/MathModelsDesign/Modules/45-Uncertainty/50-Thoughts/index.qmd
                 
              # - section: "Connections"
              #   href: content/courses/MathModelsDesign/Modules/55-Connections/listing.qmd
              #   contents:
              #   - content/courses/MathModelsDesign/Modules/55-Connections/10-GraphNetworks/index.qmd
              #   - content/courses/MathModelsDesign/Modules/55-Connections/20-Communities/index.qmd

              - section: "AI"
                href: content/courses/MathModelsDesign/Modules/100-AI/listing.qmd
                contents:                        
                - content/courses/MathModelsDesign/Modules/100-AI/10-NeuralNets/index.qmd
                - content/courses/MathModelsDesign/Modules/100-AI/20-Perceptron/index.qmd
                - content/courses/MathModelsDesign/Modules/100-AI/30-MLP/index.qmd
                - content/courses/MathModelsDesign/Modules/100-AI/40-BackProp/index.qmd
                - content/courses/MathModelsDesign/Modules/100-AI/50-GradientDescent/index.qmd
#               - content/courses/MathModelsDesign/Modules/100-AI/55-HandCalculation/index.qmd
#               - content/courses/MathModelsDesign/Modules/100-AI/60-ConveNet/index.qmd
#               - content/courses/MathModelsDesign/Modules/100-AI/200-LLMs/index.qmd

              - section: "Projects"
                href: content/courses/MathModelsDesign/Modules/1000-Projects/index.qmd
                contents:                        
                - content/courses/MathModelsDesign/Modules/1000-Projects/index.qmd
         
  page-footer:
    center: "Website made with ❤️ and [Quarto](https://quarto.org/), by Arvind V."
    right:  Hosted by Netlify [{{< iconify simple-icons netlify >}}](https://www.netlify.com).
    left:  "License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)"
    background: light
 
format:
  html:
    smooth-scroll: true
    fontsize: "medium"
    theme: yeti
    # css: 
    #   - css/fira.css
    #   - css/roboto-condensed.css
    #   - css/vollkorn.css
    #   - css/fraunces.css
    #   - css/styles.css
    #backgroundcolor: "aliceblue"
    #mainfont: Roboto Condensed
    #monofont: Fira Code
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    page-navigation: true
    back-to-top-navigation: true
    bread-crumbs: true
    code-tools: false
    code-copy: true
    code-block-border-left: "black"
    code-block-bg: "#E7FBFE"
    code-fold: false
    code-summary: "Show the Code"
    code-overflow: scroll
    code-line-numbers: false # not with code-link:true
    code-link: true
    code-annotations: true
    format-links: true
    highlight-style: tango
    reference-location: document
    cap-location: bottom
    df-print: paged
    toc: true
    fig-align: center
    fig-cap-location: bottom
    # fig-asp: 0.618
    # fig-width: 5
    # fig-height: 4
    fig-dpi: 300

    filters:
      - d2
      - tabby
      - webr
      - quarto
      - line-highlight
      - shinylive
      - gadenbuie/tachyons # Causes strange code wrapping with decimals!

    d2:
      format: svg
      embed_mode: raw
    webr:
      channel-type: "automatic"
    mermaid:
      theme: forest

    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem

  
editor: 
  source:
    markdown: 
      wrap: 72
lightbox: # Based on internal Quarto feature
  match: auto
  effect: zoom
  desc-position: right
  loop: false

knitr:
  opts_chunk: 
    tidy: 'styler'
    


