project:
  type: website

website:
  title: "Arvind Venkatadri"
  site-url: https://av-quarto.netlify.app
  description: "Trying to Play with Quarto"

  repo-url: https://github.com/arvindvenkatadri/my-quarto-website
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@arvind_v"
    image: "materials/images/twitter-card.png"

  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: rss-fill
        href: index.xml
        aria-label: RSS
      - icon: github
        href: https://github.com/arvindvenkatadri/my-quarto-website
        aria-label: GitHub repo
      - icon: twitter
        href: https://twitter.com/arvind_v
        aria-label: Arvind Twitter
        
    search: true
    pinned: true
    
  sidebar:
    style: "docked"
    search: true
    contents: auto

  page-footer:
    right: "This blog is built with ❤️ and [Quarto](https://quarto.org/)."
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://www.rstudio.com)

format:
  html:
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    code-tools: true

editor: visual

