project:
  type: website
  preview:
    port: 4200
    browser: true
execute:
  freeze: auto
  cache: true
  echo: true

website:
  page-navigation: true
  back-to-top-navigation: true
  open-graph: true
  search: true
  twitter-card: true
  title: "The Foundation Series"
  site-url: "https://av-quarto.netlify.app"
  repo-url: https://github.com/arvindvenkatadri/my-quarto-website
  description: This is the personal website of Arvind Venkatadri.

  #google-analytics: "G-2J79YYG9CZ" 
  reader-mode: true
  
  
  navbar:
    background: primary
    # foreground: "#FAF1B0"
    pinned: false
    collapse: true
    collapse-below: lg
    left: 
      - text: "Home"
        file: index.qmd
      
    right:
      # - text: Contents
      # - blog.qmd
      # - text: Content
      - icon: github
        href: https://github.com/arvindvenkatadri/my-quarto-website
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: linkedin
        href: www.linkedin.com/in/arvindvenkatadri
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com

  sidebar:
    style: floating
    background: primary
    alignment: left
    collapse-level: 2
    search: true
    contents:
      - section: "Teaching"
        contents: 
          - "---"
          - file: content/courses/Analytics/listing.qmd
            contents: 
              - "---"
              - file: content/courses/Analytics/Tools/listing.qmd
              - "---"
              - file: content/courses/Analytics/Descriptive/listing.qmd
              - "---"
              - file: content/courses/Analytics/Inference/listing.qmd
              - "---"
              - file: content/courses/Analytics/Modelling/listing.qmd
              - "---"
              - file: content/courses/Analytics/Predictive/listing.qmd
              - "---"
              - file: content/courses/Analytics/Prescriptive/listing.qmd
              - "---"
              - file: content/courses/Analytics/Workflow/listing.qmd
          - "---"
          - file: content/courses/R4Artists/listing.qmd
          - "---"
          - file: content/courses/TRIZ4ProbSolving/listing.qmd
          - "---"
          - file: content/courses/MathModelsDesign/listing.qmd
          - "---"
          - file: content/courses/NoCode/listing.qmd
          - "---"
          - file: content/courses/ISTW/listing.qmd
          - "---"
#      - text: Posts
#        file: content/posts/listing.qmd
#      - "---"
      - text: Blogs
        file: content/projects/listing.qmd
      - "---"
      - text: Slides
        file: content/slides/listing.qmd
        
  page-footer:
    center: "Website made with ❤️ and [Quarto](https://quarto.org/), by Arvind V.<br> License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    # right:
    #   - icon: github
    #     href: https://github.com/arvindvenkatadri/
    #   - icon: twitter
    #     href: https://twitter.com/arvind_v
    #   - icon: envelope
    #     href: mailto:arvind.venkatadri@gmail.com
      # - icon: rss
      #   href: blog.xml
format:
  html:
    smooth-scroll: true
    #fontsize: "large"
    theme:
      - journal
      - ember.scss
      #light: flatly
      #dark: darkly
    #backgroundcolor: cornsilk
    #backgroundcolor: "#F8F5F5"
    author: Arvind V
    mainfont: Roboto
    monofont: Fira Code
    # monofont: Playfair Display
    # fontsize: 18px
    link-external-icon: true
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    section-divs: true
    number-sections: false
    toc: true
    message: false
    warning: false
    code-tools: true
    code-block-border-left: "black"
    code-block-bg: "#E7FBFE"
    code-fold: false
    code-summary: "Show the Code"
    code-overflow: scroll
    code-line-numbers: false
    code-link: true
    code-annotations: false
    code-copy: true
    highlight-style: tango
    reference-location: document
    cap-location: bottom
    df-print: paged
    fig-align: center
    # fig-width: 5
    # fig-height: 4
    fig-dpi: 300
    
    filters:
      - d2
      - webr
      - quarto
      - line-highlight
    # - nutshell
    # - lightboxfilters:
    # - code-fullscreen
    # - first-line-indent
    d2:
      format: svg
      embed_mode: raw
    webr:
      channel-type: "automatic"
    mermaid:
      theme: forest
    
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem

  
editor: source


# twitter-card:
#   creator: "@arvind_v"
#   card-style: summary_large_image

