project:
  type: website
execute: 
  freeze: auto
preview:
    port: 4200
    browser: true
resource-path: 
  - /content/materials/*.*


website:
  page-navigation: true
  open-graph: true
  search: true
  title: "The Foundation Series in Quarto"
  site-url: "https://av-quarto.netlify.app"
  repo-url: https://github.com/arvindvenkatadri/my-quarto-website
  description: This is the personal website of Arvind Venkatadri.
  
  #google-analytics: "G-2J79YYG9CZ"
  reader-mode: true
    
  navbar:
    background: primary
    foreground: "#FAF1B0"
    left: 
      - text: "Home"
        file: index.qmd
      
    right:
      # - text: Contents
      # - blog.qmd
      # - text: Content
      - icon: github
        href: https://github.com/arvindvenkatadri/my-quarto-website
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: rss
        href: blog.xml

  sidebar:
    style: floating
    search: true
    contents:
      - text: Home
        href: blog.qmd
      - "---"
      - section: "Teaching"
        contents: 
          - section: "Data Analytics"
            contents:
              - content/courses/Data-Analytics/Modules/Descriptive-Analytics/listing.qmd
              - content/courses/Data-Analytics/Modules/Basics-of-Modeling/listing.qmd
              - content/courses/Data-Analytics/Modules/Predictive-Analytics/listing.qmd
              - content/courses/Data-Analytics/Modules/Prescriptive-Analytics/listing.qmd
          - "---"
          - content/courses/R-for-Artists/r-for-artists.qmd
          - "---"
      - text: Posts
        file: content/posts/posts.qmd
      - "---"
      - text: Projects
        file: content/projects/projects.qmd
        

format:
  html:
    smooth-scroll: true
    theme: 
      light: united
      dark: slate
    #css: ember.scss
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true

editor: visual

page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Arvind Venkatadri. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/arvindvenkatadri/
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com
      - icon: rss
        href: blog.xml
        
twitter-card:
  creator: "@arvind_v"
  card-style: summary_large_image
    

comments:
  utterances:
    repo: arvindvenkatadri/my-quarto-website
