project:
  type: website

website:
  page-navigation: true
  open-graph: true
  search: true
  title: "An Idle Mind (_quarto.yml)"
  site-url: "https://av-quarto.netlify.app"
  #google-analytics: "G-2J79YYG9CZ"
  reader-mode: true
    
  navbar:
    background: primary
    foreground: "#FAF1B0"
    right:
      - about.qmd
      - text: Content
        menu:
          - text: Posts
            aria-label: Posts
            href: posts/posts.qmd
          - text: Courses
            href: courses/courses.qmd
            aria-label: Courses
          - text: Projects
            href: projects/projects.qmd
            aria-label: Projects
          - icon: github
            href: https://github.com/arvindvenkatadri/my-quarto-website
          - icon: twitter
            href: https://twitter.com/arvind_v

  sidebar:
    style: "docked"
    search: true
    contents: auto
    
format:
  html:
    smooth-scroll: true
    theme: 
      light: journal
      dark: darkly
    css: ember.scss
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true

editor: visual

page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Arvind Venkatadri. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/arvindvenkatadri/
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com
      - icon: rss
        href: blog.xml
        
twitter-card:
  creator: "@arvind_v"
  card-style: summary_large_image
    

comments:
  utterances:
    repo: arvindvenkatadri/my-quarto-website
