project:
  type: website

website:
  page-navigation: true
  title: "Arvind Venkatadri"
  site-url: "https://av-quarto.netlify.app"
  #google-analytics: "G-2J79YYG9CZ"
  
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Arvind Venkatadri. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/arvindvenkatadri/
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com
        
  twitter-card:
    creator: "@arvind_v"
    card-style: summary_large_image
    
  navbar:
    right:
      - about.qmd
      - text: Courses, Posts, and Projects
        menu:
          - text: Posts
            aria-label: Posts
            href: posts/posts.qmd
          - text: Courses
            href: courses/courses.qmd
            aria-label: Courses
          - text: Projects
            href: projects/projects.qmd
            aria-label: Projects
          # - text: English
          #   href: posts/en.qmd
          # - text: Português
          #   href: posts/pt.qmd
          # - text: Español
          #   href: posts/es.qmd
      # - text: Series
      #   menu:
      #     - text: GitHub Actions
      #       href: series-gha.qmd
      # - text: Talks
        # menu:
        #   - text: All/Todas
        #     href: talks/index.qmd
        #   - text: English
        #     href: talks/en/index.qmd
        #   - text: Português
        #     href: talks/pt/index.qmd
        #   - text: Español
        #     href: talks/es/index.qmd
      # - text: Resume
      #   href: https://beatrizmilz.github.io/resume/index.pdf
      - icon: github
        href: https://github.com/beatrizmilz/blog-en
      - icon: twitter
        href: https://twitter.com/BeaMilz

  sidebar:
    style: "docked"
    search: true
    contents: auto
    
format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true

editor: visual

# comments:
#   giscus:
#     repo: arvindvenkatadri/
