project:
  type: website
  preview:
    port: 4200
    browser: true
execute:
  freeze: auto
  cache: true
  echo: true

website:
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph: true
  search: true
  twitter-card: true
  title: "Applied Metaphors: Learning TRIZ, Complexity, Data/Stats/ML using Metaphors"
  site-url: "https://av-quarto.netlify.app"
  repo-url: https://github.com/arvindvenkatadri/my-quarto-website
  description: This is the teaching website of Arvind Venkatadri, Adjunct Professor, DSU, India.
  favicon: "content/materials/icon-park-twotone--concept-sharing.svg"
  #google-analytics: "G-2J79YYG9CZ" 
  reader-mode: true
  
  navbar:
    background: primary
    # foreground: "#FAF1B0"
    pinned: false
    collapse: true
    collapse-below: lg
    # left: 
    #   - text: "Home"
    #     file: index.qmd
      
    right:
      # - text: Contents
      # - blog.qmd
      # - text: Content
      - icon: github
        href: https://github.com/arvindvenkatadri/my-quarto-website
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: linkedin
        href: www.linkedin.com/in/arvindvenkatadri
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com

  sidebar:
    style: docked
    background: light
    alignment: left
    collapse-level: 2
    search: true
    contents:
      - section: "Teaching"
        contents: 
          - section: "Data Analytics"
            href : content/courses/Analytics/listing.qmd
            contents: 
              - section: "Tools"
                href: content/courses/Analytics/Tools/listing.qmd
                contents:
                - content/courses/Analytics/Tools/10-Intro-to-R/r-intro.qmd
                - content/courses/Analytics/Tools/20-Intro-to-Radiant/radiant.qmd
                - content/courses/Analytics/Tools/30-Intro-to-Orange/orange.qmd
              
              - section: "Descriptive Analytics"
                href: content/courses/Analytics/Descriptive/listing.qmd
                contents: 
                - content/courses/Analytics/Descriptive/Modules/05-NatureData/nature-data.qmd
                - content/courses/Analytics/Descriptive/Modules/10-FavStats/intro-favstats.qmd
                - content/courses/Analytics/Descriptive/Modules/20-Distributions/intro-dist.qmd
                - content/courses/Analytics/Descriptive/Modules/30-Correlations/intro-corr.qmd
                - content/courses/Analytics/Descriptive/Modules/40-CatData/index.qmd
                - content/courses/Analytics/Descriptive/Modules/45-SurveyData/index.qmd
                - content/courses/Analytics/Descriptive/Modules/50-Time/time-v2.qmd
                - content/courses/Analytics/Descriptive/Modules/60-PartWhole/part-whole.qmd
                - content/courses/Analytics/Descriptive/Modules/70-EvolutionFlow/evol-flow.qmd
                - content/courses/Analytics/Descriptive/Modules/80-Ranking/ranking.qmd
                - content/courses/Analytics/Descriptive/Modules/90-Space/spatial.qmd
                - content/courses/Analytics/Descriptive/Modules/100-Networks/networks.qmd
                - content/courses/Analytics/Descriptive/Modules/180-RefMat/other-tools.qmd
                - content/courses/Analytics/Descriptive/Modules/200-EDAWorkflow/eda-workflow.qmd
              
              - section: "Statistical Inference"
                href: content/courses/Analytics/Inference/listing.qmd
                contents: 
                - content/courses/Analytics/Inference/Modules/10-Intro/intro-inference.qmd
                - content/courses/Analytics/Inference/Modules/20-SampProb/sampling.qmd
                - content/courses/Analytics/Inference/Modules/50-Bootstrap/index.qmd
                - content/courses/Analytics/Inference/Modules/100-OneMean/single-mean.qmd
                - content/courses/Analytics/Inference/Modules/110-TwoMeans/two-means.qmd
                - content/courses/Analytics/Inference/Modules/120-PairedMeans/paired-means.qmd
                - content/courses/Analytics/Inference/Modules/130-ThreeMeansOrMore/ANOVA.qmd
                - content/courses/Analytics/Inference/Modules/150-Correlation/single_corr.qmd
                - content/courses/Analytics/Inference/Modules/180-OneProp/single-prop.qmd
                - content/courses/Analytics/Inference/Modules/190-TwoProp/two-props.qmd
              
              - section: "Inferential Modelling"
                href: content/courses/Analytics/Modelling/listing.qmd
                contents: 
                - content/courses/Analytics/Modelling/Modules/LinReg/LinReg.qmd
                - content/courses/Analytics/Modelling/Modules/LogReg/logistic.qmd
                - content/courses/Analytics/Modelling/Modules/ModelTimeSeries/index.qmd
              
              - section: "Predictive Modelling"
                href : content/courses/Analytics/Predictive/listing.qmd
                contents: 
                - content/courses/Analytics/Predictive/Modules/10-IntroOrange/index.qmd
                - content/courses/Analytics/Predictive/Modules/20-Regression/index.qmd
                - content/courses/Analytics/Predictive/Modules/30-Classification/index.qmd
                - content/courses/Analytics/Predictive/Modules/40-Clustering/index.qmd
                
              - section: "Prescriptive Modelling"
                href : content/courses/Analytics/Prescriptive/listing.qmd
                contents: 
                - content/courses/Analytics/Prescriptive/Modules/10-IntroLinearProg/index.qmd
                - content/courses/Analytics/Prescriptive/Modules/20-SimplexMethodIntuitive/index.qmd
                - content/courses/Analytics/Prescriptive/Modules/30-SimlexMethodExcel/index.qmd
              
              - section: "Workflow"
                href : content/courses/Analytics/Workflow/listing.qmd               
                contents: 
                - content/courses/Analytics/Workflow/Modules/10-Reports-flextable/index.qmd
                - content/courses/Analytics/Workflow/Modules/20-Dashboards-quarto/index.qmd

          - section: "R for Artists and Managers"
            href: content/courses/R4Artists/listing.qmd
            contents: 
            - content/courses/R4Artists/Modules/10-Basics/index.qmd
            - content/courses/R4Artists/Modules/20-intro/index.qmd
            - content/courses/R4Artists/Modules/30-quarto/index.qmd
            - content/courses/R4Artists/Modules/40-working-in-r/index.qmd
            - content/courses/R4Artists/Modules/50-working-in-tidyverse/index.qmd
            - content/courses/R4Artists/Modules/60-GoG/index.qmd
            - content/courses/R4Artists/Modules/70-wizardy/index.qmd
            - content/courses/R4Artists/Modules/80-htmlwidgets/htmlwidgets.qmd
            - content/courses/R4Artists/Modules/90-GoM/spatial.qmd
            - content/courses/R4Artists/Modules/100-GoN/index.qmd
            - content/courses/R4Artists/Modules/110-GoD/index.qmd
            - content/courses/R4Artists/Modules/120-time/index.qmd
            - content/courses/R4Artists/Modules/130-purrr/purrr.qmd
            - content/courses/R4Artists/Modules/200-wrap/index.Rmd
            - content/courses/R4Artists/Modules/300-website/index.Rmd
            
          - section: "ML for Artists and Managers"
            href: content/courses/ML4Artists/listing.qmd
            contents: 
            - content/courses/ML4Artists/Modules/10-IntroOrange/index.qmd
            - content/courses/ML4Artists/Modules/20-Regression/index.qmd
            - content/courses/ML4Artists/Modules/30-Classification/index.qmd
            - content/courses/ML4Artists/Modules/40-Clustering/index.qmd
            - content/courses/ML4Artists/Modules/50-ModelTimeSeries/index.qmd
            
          - section: "TRIZ for Problem Solving"
            href: content/courses/TRIZ4ProbSolving/listing.qmd
            contents: 
            - content/courses/TRIZ4ProbSolving/Modules/10-Flow-and-Play/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/20-Cultural-Capital/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/30-MBTI-Big-5/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/35-Domain-Field-Self/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/37-What-Am-I-Thinking-Of/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/40-Parallel-Thinking/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/50-Metaphoric-Thinking/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/60-Problems-and-Contradictions/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/70-TRIZ-Resources/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/75-TRIZ-Ideal-Final-Result/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/80-A-Contradictory-Language/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/90-TRIZ-Contradiction-Matrix/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/100-TRIZ-Laws-of-Evolution/index.qmd
            - content/courses/TRIZ4ProbSolving/Modules/200-TRIZ-Advanced-Stuff/index.qmd
            
          - section: "Math Models in Design"
            href: content/courses/MathModelsDesign/listing.qmd
            # file: content/courses/MathModelsDesign/listing.qmd
            contents:
            # - content/courses/MathModelsDesign/Modules/10-IteratedGames/iteratedGames.qmd
            # - content/courses/MathModelsDesign/Modules/30-SchellingPoints/schelling.qmd
            # - content/courses/MathModelsDesign/Modules/60-Randomness/randomness.qmd
            - content/courses/MathModelsDesign/Modules/05-Tools/index.qmd
            - content/courses/MathModelsDesign/Modules/90-WorkingWithShape/index.qmd
            - content/courses/MathModelsDesign/Modules/100-WorkingWithSound/index.qmd
            - content/courses/MathModelsDesign/Modules/40-WorkingWithNetworks/index.qmd
            - content/courses/MathModelsDesign/Modules/80-WorkingWithChance/index.qmd
            - content/courses/MathModelsDesign/Modules/120-WorkingWithText/index.qmd
            - content/courses/MathModelsDesign/Modules/140-WorkingWithTime/index.qmd
            - content/courses/MathModelsDesign/Modules/160-WorkingWithThoughts/index.qmd
            
          - section: "Data Vis with No Code"
            href: content/courses/NoCode/listing.qmd
            contents:
            - content/courses/NoCode/Modules/01-NatureofData/index.qmd
            - content/courses/NoCode/Modules/05-IntroductiontoOrange/index.qmd
            - content/courses/NoCode/Modules/10-SummaryStats/index.qmd
            - content/courses/NoCode/Modules/20-Histograms/index.qmd
            - content/courses/NoCode/Modules/22-BarCharts/index.qmd
            - content/courses/NoCode/Modules/28-BoxPlotsViolins/index.qmd
            - content/courses/NoCode/Modules/30-ScatterPlots/index.qmd
            - content/courses/NoCode/Modules/32-LinePlots/index.qmd
            - content/courses/NoCode/Modules/35-MosaicCharts/index.qmd
            - content/courses/NoCode/Modules/40-SankeyCharts/index.qmd
            - content/courses/NoCode/Modules/50-PiesDonutsParliaments/index.qmd            
            - content/courses/NoCode/Modules/54-Trees/index.qmd             
            - content/courses/NoCode/Modules/60-LollipopsBumpsRadars/index.qmd
            - content/courses/NoCode/Modules/70-Maps/index.qmd             
            - content/courses/NoCode/Modules/80-Time/index.qmd             
            - content/courses/NoCode/Modules/100-Networks/index.qmd
            - content/courses/NoCode/Modules/140-SurveyData/index.qmd
            - content/courses/NoCode/Modules/150-NoFreeHunch/index.qmd
            
          - text: "Literary Jukebox: In Short, the World"
            href: content/courses/ISTW/listing.qmd
            file: content/courses/ISTW/listing.qmd
            
      - text: Posts
        file: content/posts/listing.qmd
  
      - text: Blogs
        file: content/projects/listing.qmd

      # - text: Slides
      #   file: content/slides/listing.qmd
        
  page-footer:
    center: "Website made with ❤️ and [Quarto](https://quarto.org/), by Arvind V.<br> License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)<br> Hosted by Netlify [{{< iconify simple-icons netlify >}}](https://www.netlify.com)."
    # right:
    #   - icon: github
    #     href: https://github.com/arvindvenkatadri/
    #   - icon: twitter
    #     href: https://twitter.com/arvind_v
    #   - icon: envelope
    #     href: mailto:arvind.venkatadri@gmail.com
      # - icon: rss
      #   href: blog.xml
format:
  html:
    smooth-scroll: true
    fontsize: "medium"
    theme:
      light: 
        - flatly
        - gfonts/css/flatly.scss
        - gfonts/css/sofia-sans-extra-condensed.css
        - gfonts/css/sofia-sans.css
        - gfonts/css/sofia-sans-condensed.css
        - gfonts/css/noto-serif.css
        - gfonts/css/roboto.css
        - gfonts/css/styles.css
      dark: darkly
    #backgroundcolor: cornsilk
    #backgroundcolor: "#F8F5F5"
    author: Arvind V
    mainfont: 'sofia sans'
    monofont: Fira Code
    link-external-icon: true
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    section-divs: true
    number-sections: false
    toc: true
    message: false
    warning: false
    code-tools: false
    code-copy: true
    code-block-border-left: "black"
    code-block-bg: "#E7FBFE"
    code-fold: false
    code-summary: "Show the Code"
    code-overflow: scroll
    code-line-numbers: false
    code-link: true
    code-annotations: false
    highlight-style: tango
    reference-location: document
    cap-location: bottom
    df-print: paged
    fig-align: center
    # fig-width: 5
    # fig-height: 4
    fig-dpi: 300
    
    filters:
      - d2
      - webr
      - quarto
      - line-highlight
      - shinylive
    # - lightbox # based on extension
    # - nutshell
    # - lightboxfilters:
    # - code-fullscreen
    # - first-line-indent
    d2:
      format: svg
      embed_mode: raw
    webr:
      channel-type: "automatic"
    mermaid:
      theme: forest
    
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem

  
editor: source
lightbox: # Based on internal Quarto feature
  match: auto
  effect: zoom
  desc-position: right
  loop: false
  
# twitter-card:
#   creator: "@arvind_v"
#   card-style: summary_large_image

