project:
  type: website
  preview:
    port: 4200
    browser: true
execute:
  freeze: true
  cache: true

website:
  page-navigation: true
  open-graph: true
  search: true
  title: "The Foundation Series"
  site-url: "https://av-quarto.netlify.app"
  repo-url: https://github.com/arvindvenkatadri/my-quarto-website
  description: This is the personal website of Arvind Venkatadri.

  #google-analytics: "G-2J79YYG9CZ" 
  reader-mode: true
    
  navbar:
    background: primary
    foreground: "#FAF1B0"
    left: 
      - text: "Home"
        file: index.qmd
      
    right:
      # - text: Contents
      # - blog.qmd
      # - text: Content
      - icon: github
        href: https://github.com/arvindvenkatadri/my-quarto-website
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: rss
        href: blog.xml

  sidebar:
    style: floating
    search: true
    contents:
      - text: Home
        file: blog.qmd
      - "---"
      - section: "Teaching"
        contents: 
          - section: "Data Analytics"
            contents: 
              - "---"
              - file: content/courses/Data-Analytics/Descriptive-Analytics/listing.qmd
              - "---"
              - file: content/courses/Data-Analytics/Basics-of-Modeling/listing.qmd
              - "---"
              - file: content/courses/Data-Analytics/Predictive-Analytics/listing.qmd
              - "---"
              - file: content/courses/Data-Analytics/Prescriptive-Analytics/listing.qmd
              - "---"
          - file: content/courses/R-for-Artists/listing.qmd
          - "---"
      - text: Posts
        file: content/posts/listing.qmd
      - "---"
      - text: Projects
        file: content/projects/listing.qmd
        

format:
  html:
    smooth-scroll: true
    theme: 
      light: united
      dark: slate
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true
    # mainfont: Playfair Display
    # monofont: Playfair Display
    code-block-border-left: true
    code-block-bg: true
    section-divs: true
    fig-dpi: 600
    
  
editor: visual

page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Arvind Venkatadri. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/arvindvenkatadri/
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com
      - icon: rss
        href: blog.xml
        
twitter-card:
  creator: "@arvind_v"
  card-style: summary_large_image

