project:
  type: website
  preview:
    port: 4200
    browser: true
execute:
  freeze: auto
  cache: true

website:
  page-navigation: true
  open-graph: true
  search: true
  title: "The Foundation Series"
  site-url: "https://av-quarto.netlify.app"
  repo-url: https://github.com/arvindvenkatadri/my-quarto-website
  description: This is the personal website of Arvind Venkatadri.

  #google-analytics: "G-2J79YYG9CZ" 
  reader-mode: false
  
  
  navbar:
    background: primary
    # foreground: "#FAF1B0"
    left: 
      - text: "Home"
        file: index.qmd
      
    right:
      # - text: Contents
      # - blog.qmd
      # - text: Content
      - icon: github
        href: https://github.com/arvindvenkatadri/my-quarto-website
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: linkedin
        href: www.linkedin.com/in/arvindvenkatadri

  sidebar:
    style: docked
    background: primary
    alignment: left
    collapse-level: 2
    search: true
    contents:
      - section: "Teaching"
        contents: 
          - "---"
          - file: content/courses/Analytics/listing.qmd
            contents: 
              - "---"
              - file: content/courses/Analytics/Tools/listing.qmd
              - "---"
              - file: content/courses/Analytics/Descriptive/listing.qmd
              - "---"
              - file: content/courses/Analytics/Inference/listing.qmd
              - "---"
              - file: content/courses/Analytics/Modelling/listing.qmd
              - "---"
              - file: content/courses/Analytics/Predictive/listing.qmd
              - "---"
              - file: content/courses/Analytics/Prescriptive/listing.qmd
              - "---"
              - file: content/courses/Analytics/Workflow/listing.qmd
          - "---"
          - file: content/courses/R4Artists/listing.qmd
          - "---"
          - file: content/courses/TRIZ4ProbSolving/listing.qmd
          - "---"
          - file: content/courses/MathModelsDesign/listing.qmd
          - "---"
          - file: content/courses/NoCode/listing.qmd
          - "---"
          - file: content/courses/ISTW/listing.qmd
          - "---"
      - text: Posts
        file: content/posts/listing.qmd
      - "---"
      - text: Blogs
        file: content/projects/listing.qmd
        
  page-footer:
    left: "Website made with 💜 and [Quarto](https://quarto.org/), by Arvind Venkatadri. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/arvindvenkatadri/
      - icon: twitter
        href: https://twitter.com/arvind_v
      - icon: envelope
        href: mailto:arvind.venkatadri@gmail.com
      # - icon: rss
      #   href: blog.xml
format:
  html:
    smooth-scroll: true
    theme:
      - lux
      - ember.scss
      #light: flatly
      #dark: darkly
    backgroundcolor: cornsilk
    monofont: Fira Code
    # fontsize: 18px
    # mainfont: Playfair Display
    # monofont: Playfair Display
    footnotes-hover: true
    link-external-icon: true
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    section-divs: true
    toc: true
    code-link: true
    message: false
    warning: false
    code-annotations: hover
    code-block-border-left: "black"
    code-block-bg: "moccasin"
    code-fold: false
    code-summary: Show the Code
    code-overflow: scroll
    code-line-numbers: "black"
    highlight-style: tango
    reference-location: margin
    cap-location: margin
    df-print: paged
    fig-align: center
    #fig-dpi: 600
    # filters: 
    #   - nutshell
    #   - lightbox
    mermaid:
      theme: forest
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem

  
editor: visual


# twitter-card:
#   creator: "@arvind_v"
#   card-style: summary_large_image

